#!/bin/sh
#
# Screen script that launches remote-viewer. Can be called from lts.conf
# like this:
#   SCREEN_07="remote-viewer -f spice://server:port"
# or like this:
#   SCREEN_07="remote-viewer"
#
# Copyright (c) 2016 Jeffrey Hein <http://jphein.com>
#
# This software is licensed under the GNU General Public License version 2,
# the full text of which can be found in the COPYING file.

. /usr/share/ltsp/screen-x-common
# segfaults if HOME is unset.
export HOME=${HOME:-/root}

# The same screen script can be used for other spice viewers too, by just symlinking
# screen.d/{otherviewer} to screen.d/remote-viewer.
basename=${0##*/}

if ! type $basename >/dev/null 2>&1; then
    echo "$basename couldn't be found."
    if [ "$basename" = "remote-viewer" ]; then
        echo "Please make sure you have installed remote-viewer into your client chroot."
    fi
    read nothing
    exit 1
fi

# Make XINITRC_DAEMON default to "True", to prevent X from restarting after
# logout. If you don't want that, force XINITRC_DAEMON=False in lts.conf.
export XINITRC_DAEMON="${XINITRC_DAEMON-True}"

# If no parameters were passed, set some reasonable defaults.
if [ -z "$*" ]; then
    SPICE_OPTIONS=${SPICE_OPTIONS:-"-f"}
    SPICE_SERVER=${SPICE_SERVER:-"spice://server:5900"}
fi

COMMAND="$basename $* $SPICE_OPTIONS $SPICE_SERVER"

# The following logic is described at the top of xinitrc.
exec xinit /usr/share/ltsp/xinitrc "$COMMAND" -- "$DISPLAY" "vt${TTY}" -nolisten tcp $X_ARGS >/dev/null
