#!/bin/sh
#
# Screen script that launches a welcome screen. Can be called from lts.conf
# like this:
#   SCREEN_07="welcome"
#
# Copyright (c) 2011 Alkis Georgopoulos <http://alkisg.mysch.gr>
#
# This software is licensed under the GNU General Public License version 2,
# the full text of which can be found in the COPYING file.

. /usr/share/ltsp/screen-x-common
# xfreerdp segfaults if HOME is unset.
export HOME=${HOME:-/root}

# Make XINITRC_DAEMON default to "True", to prevent X from restarting after
# logout. If you don't want that, force XINITRC_DAEMON=False in lts.conf.
export XINITRC_DAEMON="${XINITRC_DAEMON-True}"

COMMAND='zenity --text-info --title="$WELCOME_TITLE" --width=$WELCOME_WIDTH --height=$WELCOME_HEIGHT  --html --url="$WELCOME_URL" $* '

# The following logic is described at the top of xinitrc.
exec xinit /usr/share/ltsp/xinitrc "$COMMAND" -- "$DISPLAY" "vt${TTY}" -nolisten tcp $X_ARGS >/dev/null
