==============================================================================

                             Welcome to BoXenLinux

            BoXen baby (client) will net boot in 30 seconds...

        If instead you'd like something else to happen:


        To install BoXen brain (server) type                    : brain

                        or

        To install BoXen baby (client) type                     : baby

                        or

        To boot to your first local hard drive type             : hd


                                                      and press : <enter>

==============================================================================
