#!/bin/sh
#
# Screen script that launches vncviewer. Can be called from lts.conf
# like this:
#   SCREEN_07="vncviewer -fullscreen server"
# or like this:
#   SCREEN_07="vncviewer"
#
# Copyright (c) 2016 Jeffrey Hein <http://jphein.com>
#
# This software is licensed under the GNU General Public License version 2,
# the full text of which can be found in the COPYING file.

. /usr/share/ltsp/screen-x-common
# segfaults if HOME is unset.
export HOME=${HOME:-/root}

# The same screen script can be used for other vncviwers too, by just symlinking
# screen.d/{otherviewer} to screen.d/vncviewer.
basename=${0##*/}

if ! type $basename >/dev/null 2>&1; then
    echo "$basename couldn't be found."
    if [ "$basename" = "vncviewer" ]; then
        echo "Please make sure you have installed xtightvncviwer into your client chroot."
    fi
    read nothing
    exit 1
fi

# Make XINITRC_DAEMON default to "True", to prevent X from restarting after
# logout. If you don't want that, force XINITRC_DAEMON=False in lts.conf.
export XINITRC_DAEMON="${XINITRC_DAEMON-True}"

# If no parameters were passed, set some reasonable defaults.
if [ -z "$*" ]; then
    RDP_OPTIONS=${VNC_OPTIONS:-"-fullscreen"}
    RDP_SERVER=${VNC_SERVER:-"server"}
fi

COMMAND="echo $VNC_PASSWORD | $basename $* $VNC_OPTIONS $VNC_SERVER"

# The following logic is described at the top of xinitrc.
exec xinit /usr/share/ltsp/xinitrc "$COMMAND" -- "$DISPLAY" "vt${TTY}" -nolisten tcp $X_ARGS >/dev/null
